# Klasyfikacja z wykorzystaniem sieci neuronowych

In [1]:
import numpy as np
from keras.datasets import mnist
import keras
from keras import layers
from sklearn.metrics import classification_report, confusion_matrix

# Wczytanie i konwersja danych

### Wczytanie bazy z biblioteki tenserflow

In [2]:
training_set, test_set = mnist.load_data()

### Podział na zbiory treningowe i testowe

In [3]:
X_train, y_train = training_set
X_test, y_test = test_set

### Kształt danych

In [4]:
print(X_train.shape)
# ilość przykładów x wysokość obrazu x szerokość obrazu

(60000, 28, 28)


### Dodanie wymiaru kanału dla zbioru testowego i treningowego

In [5]:
X_train = np.expand_dims(X_train, -1)
X_test = np.expand_dims(X_test, -1)

### Wypisanie nowego kszałtu danych

In [6]:
print(X_train.shape)

(60000, 28, 28, 1)


### Przeskalowanie wartości pikseli do zakresu 0.0 - 1.0

In [7]:
X_train = X_train.astype(np.float64) / 255.0  
X_test = X_test.astype(np.float64) / 255.0

# Przygotowanie eksperymentu

### Zefiniowanie wartści definujących warunki eksperymentu

In [8]:
# ilość klas do klasyfikacji (10 klas, bo cyfry są od 0 - 9)
num_classes = 10

# rozmiar wejścia na sieć dla obrazu w skali szarości z jednym kanałem
input_shape = (28, 28, 1)

# rozmiar paczki będącej jednorazowym wejściem na sieć
batch_size = 128

# ilość epok uczenia ( liczbę wpok interpretujemy “pokazanie” wszystkich przykładów modelowi )
epochs = 30

### Przygotowanie modelu

In [9]:
model = keras.Sequential(
        [
            keras.Input(shape=input_shape),
            keras.layers.Flatten(),
            layers.Dense(num_classes, activation="softmax")
        ]
    )

### Podsumowanie

In [10]:
model.summary()

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 flatten (Flatten)           (None, 784)               0         
                                                                 
 dense (Dense)               (None, 10)                7850      
                                                                 
Total params: 7,850
Trainable params: 7,850
Non-trainable params: 0
_________________________________________________________________


### Kompilacja

In [11]:
model.compile(loss="sparse_categorical_crossentropy", optimizer="adam", metrics=["accuracy"])

# Uczenie modelu

In [12]:
model.fit(X_train, y_train, batch_size=batch_size, epochs=epochs, validation_split=0.2)

Epoch 1/30
375/375 [==============================] - 3s 6ms/step - loss: 0.7421 - accuracy: 0.8169 - val_loss: 0.4098 - val_accuracy: 0.8952
Epoch 2/30
375/375 [==============================] - 2s 6ms/step - loss: 0.3891 - accuracy: 0.8963 - val_loss: 0.3336 - val_accuracy: 0.9099
Epoch 3/30
375/375 [==============================] - 2s 5ms/step - loss: 0.3381 - accuracy: 0.9069 - val_loss: 0.3078 - val_accuracy: 0.9159
Epoch 4/30
375/375 [==============================] - 2s 6ms/step - loss: 0.3140 - accuracy: 0.9132 - val_loss: 0.2938 - val_accuracy: 0.9191
Epoch 5/30
375/375 [==============================] - 3s 7ms/step - loss: 0.3002 - accuracy: 0.9168 - val_loss: 0.2846 - val_accuracy: 0.9224
Epoch 6/30
375/375 [==============================] - 2s 6ms/step - loss: 0.2903 - accuracy: 0.9195 - val_loss: 0.2788 - val_accuracy: 0.9231
Epoch 7/30
375/375 [==============================] - 2s 6ms/step - loss: 0.2834 - accuracy: 0.9209 - val_loss: 0.2734 - val_accuracy: 0.9248
Epoch 

Obserwujemy spadekk funkcji kosztu (loss) oraz wzrost metryki accuracy z epoki na epokę na zbiorze uczącym i walidacyjnym.

# Ocena modelu

In [13]:
from sklearn.metrics import classification_report, confusion_matrix

# Generacja odpowiedzi modelu n zbiorze testowym

In [14]:
y_probab = model.predict(X_test)
y_pred = np.argmax(y_probab, axis=1)

print(classification_report(y_test, y_pred))

313/313 [==============================] - 2s 5ms/step
              precision    recall  f1-score   support

           0       0.95      0.98      0.97       980
           1       0.97      0.98      0.98      1135
           2       0.91      0.91      0.91      1032
           3       0.94      0.88      0.91      1010
           4       0.94      0.93      0.93       982
           5       0.90      0.88      0.89       892
           6       0.95      0.95      0.95       958
           7       0.92      0.93      0.93      1028
           8       0.87      0.91      0.89       974
           9       0.92      0.91      0.91      1009

    accuracy                           0.93     10000
   macro avg       0.93      0.93      0.93     10000
weighted avg       0.93      0.93      0.93     10000



In [15]:
print(confusion_matrix(y_test, y_pred))

[[ 964    0    1    2    0    6    4    2    1    0]
 [   0 1116    3    1    0    1    4    2    8    0]
 [   4    8  939   10    6    4   11    8   39    3]
 [   5    0   27  888    0   40    3   12   29    6]
 [   1    2    8    1  914    0    8    5   10   33]
 [   9    3    7   19    7  786   12    9   32    8]
 [  13    3    9    1    7   12  910    1    2    0]
 [   1    6   24    5    6    1    0  958    2   25]
 [   7    6   10   14    8   21    7   11  883    7]
 [  11    7    1    7   26    6    0   29    8  914]]


# Uczenie modeli nieliniowych

### Model MLP

In [18]:
model = keras.Sequential(
        [
            keras.Input(shape=input_shape),
            keras.layers.Flatten(),
            layers.Dense(64, activation="tanh"),
            layers.Dense(128, activation="tanh"),
            layers.Dense(num_classes, activation="softmax")
        ]
    )

model.summary()

Model: "sequential_3"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 flatten_3 (Flatten)         (None, 784)               0         
                                                                 
 dense_5 (Dense)             (None, 64)                50240     
                                                                 
 dense_6 (Dense)             (None, 128)               8320      
                                                                 
 dense_7 (Dense)             (None, 10)                1290      
                                                                 
Total params: 59,850
Trainable params: 59,850
Non-trainable params: 0
_________________________________________________________________


In [20]:
model.compile(loss="sparse_categorical_crossentropy", optimizer="adam", metrics=["accuracy"])
model.fit(X_train, y_train, batch_size=batch_size, epochs=epochs, validation_split=0.2)

Epoch 1/30
375/375 [==============================] - 3s 7ms/step - loss: 0.4014 - accuracy: 0.8869 - val_loss: 0.2242 - val_accuracy: 0.9357
Epoch 2/30
375/375 [==============================] - 3s 7ms/step - loss: 0.1903 - accuracy: 0.9442 - val_loss: 0.1711 - val_accuracy: 0.9508
Epoch 3/30
375/375 [==============================] - 3s 7ms/step - loss: 0.1382 - accuracy: 0.9590 - val_loss: 0.1446 - val_accuracy: 0.9582
Epoch 4/30
375/375 [==============================] - 3s 7ms/step - loss: 0.1081 - accuracy: 0.9685 - val_loss: 0.1207 - val_accuracy: 0.9638
Epoch 5/30
375/375 [==============================] - 3s 7ms/step - loss: 0.0869 - accuracy: 0.9739 - val_loss: 0.1243 - val_accuracy: 0.9653
Epoch 6/30
375/375 [==============================] - 3s 7ms/step - loss: 0.0709 - accuracy: 0.9783 - val_loss: 0.1036 - val_accuracy: 0.9700
Epoch 7/30
375/375 [==============================] - 3s 7ms/step - loss: 0.0591 - accuracy: 0.9824 - val_loss: 0.1040 - val_accuracy: 0.9696
Epoch 

In [21]:
y_probab = model.predict(X_test)
y_pred = np.argmax(y_probab, axis=1)

print(classification_report(y_test, y_pred))
print(confusion_matrix(y_test, y_pred))

313/313 [==============================] - 1s 4ms/step
              precision    recall  f1-score   support

           0       0.97      0.99      0.98       980
           1       0.99      0.99      0.99      1135
           2       0.97      0.97      0.97      1032
           3       0.95      0.98      0.96      1010
           4       0.98      0.98      0.98       982
           5       0.97      0.96      0.97       892
           6       0.98      0.98      0.98       958
           7       0.97      0.97      0.97      1028
           8       0.97      0.96      0.97       974
           9       0.98      0.96      0.97      1009

    accuracy                           0.97     10000
   macro avg       0.97      0.97      0.97     10000
weighted avg       0.97      0.97      0.97     10000

[[ 973    0    1    2    0    2    1    1    0    0]
 [   1 1122    1    4    0    1    2    1    3    0]
 [   6    1 1005    5    3    0    2    6    4    0]
 [   0    0    2  988    0 

### Sieć konwolucyjna

In [23]:
model = keras.Sequential(
        [
            keras.Input(shape=input_shape),
            layers.Conv2D(32, kernel_size=(3, 3), activation="relu"),
            layers.MaxPooling2D(pool_size=(2, 2)),
            layers.Conv2D(64, kernel_size=(3, 3), activation="relu"),
            layers.MaxPooling2D(pool_size=(2, 2)),
            layers.Flatten(),
            layers.Dropout(0.5),
            layers.Dense(num_classes, activation="softmax"),
        ]
    )

model.summary()

Model: "sequential_5"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 conv2d_4 (Conv2D)           (None, 26, 26, 32)        320       
                                                                 
 max_pooling2d_4 (MaxPooling  (None, 13, 13, 32)       0         
 2D)                                                             
                                                                 
 conv2d_5 (Conv2D)           (None, 11, 11, 64)        18496     
                                                                 
 max_pooling2d_5 (MaxPooling  (None, 5, 5, 64)         0         
 2D)                                                             
                                                                 
 flatten_5 (Flatten)         (None, 1600)              0         
                                                                 
 dropout_2 (Dropout)         (None, 1600)             

In [24]:
model.compile(loss="sparse_categorical_crossentropy", optimizer="adam", metrics=["accuracy"])
model.fit(X_train, y_train, batch_size=batch_size, epochs=epochs, validation_split=0.2)

Epoch 1/30
375/375 [==============================] - 26s 68ms/step - loss: 0.3886 - accuracy: 0.8823 - val_loss: 0.1046 - val_accuracy: 0.9694
Epoch 2/30
375/375 [==============================] - 24s 63ms/step - loss: 0.1157 - accuracy: 0.9647 - val_loss: 0.0693 - val_accuracy: 0.9800
Epoch 3/30
375/375 [==============================] - 23s 61ms/step - loss: 0.0888 - accuracy: 0.9726 - val_loss: 0.0584 - val_accuracy: 0.9833
Epoch 4/30
375/375 [==============================] - 23s 62ms/step - loss: 0.0751 - accuracy: 0.9763 - val_loss: 0.0493 - val_accuracy: 0.9858
Epoch 5/30
375/375 [==============================] - 24s 64ms/step - loss: 0.0625 - accuracy: 0.9802 - val_loss: 0.0459 - val_accuracy: 0.9872
Epoch 6/30
375/375 [==============================] - 26s 68ms/step - loss: 0.0577 - accuracy: 0.9828 - val_loss: 0.0443 - val_accuracy: 0.9874
Epoch 7/30
375/375 [==============================] - 25s 67ms/step - loss: 0.0546 - accuracy: 0.9834 - val_loss: 0.0387 - val_accuracy:

In [25]:
y_probab = model.predict(X_test)
y_pred = np.argmax(y_probab, axis=1)

print(classification_report(y_test, y_pred))
print(confusion_matrix(y_test, y_pred))

313/313 [==============================] - 8s 25ms/step
              precision    recall  f1-score   support

           0       0.99      1.00      1.00       980
           1       0.99      1.00      0.99      1135
           2       0.99      0.99      0.99      1032
           3       1.00      0.99      0.99      1010
           4       0.99      0.99      0.99       982
           5       0.99      0.99      0.99       892
           6       1.00      0.99      0.99       958
           7       0.98      0.99      0.99      1028
           8       0.99      0.99      0.99       974
           9       0.99      0.99      0.99      1009

    accuracy                           0.99     10000
   macro avg       0.99      0.99      0.99     10000
weighted avg       0.99      0.99      0.99     10000

[[ 977    0    1    0    0    0    0    1    1    0]
 [   0 1131    3    0    0    0    1    0    0    0]
 [   0    1 1026    0    0    0    0    5    0    0]
 [   0    0    3 1002    0

Sieć konwolucyjna dała najlepsze wyniki z pośród badanych modeli. Zajęła ona jednak najwięcej czasu.